modified:   imgtool/imgtool 	modified:   imgtool/imgtool.lib 	new file:   imgtool/install.sh 	modified:   imgtool/lib/un_mount_partitions

diff --git a/imgtool/lib/un_mount_partitions b/imgtool/lib/un_mount_partitions
--- a/imgtool/lib/un_mount_partitions
+++ b/imgtool/lib/un_mount_partitions
@@ -2,6 +2,11 @@
 un_mount_partitions() {
 	local WORKDIR=${1}
 
+	if [ ! -f "${WORKDIR}/imgtool-mount-points" ]; then
+		echo $(gettext "Could not find the file imgtool-mount-points in the work directory") ; echo
+		exit 1
+	fi
+
 	echo $(gettext "umount partitions") ; echo
 	cat ${WORKDIR}/imgtool-mount-points | cut -f3 -d: | \
 	while read MOUNTPOINT
