On branch master
Changes to be committed:

new file:   bash/kernel-build/.knl_exports
deleted:    bash/kernel-build/exports
modified:   bash/kernel-build/knl_build
new file:   bash/kernel-build/knl_defconfig
deleted:    bash/kernel-build/knl_deploy
modified:   bash/kernel-build/knl_imod
modified:   bash/kernel-build/knl_modules
modified:   bash/kernel-build/knl_mrproper
modified:   bash/kernel-build/knl_oldconfig
modified:   bash/kernel-build/knl_zipmodules
deleted:    bash/kernel-build/mnt_rpi_card

diff --git a/bash/kernel-build/knl_imod b/bash/kernel-build/knl_imod
--- a/bash/kernel-build/knl_imod
+++ b/bash/kernel-build/knl_imod
@@ -1,12 +1,40 @@
 #!/bin/bash
 # Installs the built kernel modules into directory
 # controlled by ${MODULES_TEMP}
-# See .bashrc for environment settings
+
+if [ $# -ne 1 ]; then
+	echo "Usage: $0 <kernel-root>"
+	echo "Example: $0 ~/linux-rpi-3.6.y"
+	echo
+	exit 1
+fi
+
+if [ ! -d $1 ]; then
+	echo "There is no path to $1"
+	exit 1
+fi
+
+if [ ! -f "$1/linux/MAINTAINERS" ]; then
+	echo "$1/linux does not look like a valid kernel source tree"
+	exit 1
+fi
+
+# will faile if the path to the script contains an underscore:
+BN=`$(basename $0)
+SCRPT=${BN##*_}.script
+
+export KERNEL_ROOT=$1
+
+# this has to come after KERNEL_ROOT is set above:
+[[ -f ~/.knl_exports ]] && . ~/.knl_exports
+
 
 cd ${KERNEL_SRC}
-date > ~/modinstall.script
-make O=${KERNEL_BUILD} ARCH=arm CROSS_COMPILE=${CCPREFIX} INSTALL_MOD_PATH=${MODULES_TEMP} modules_install &>> ~/modinstall.script
-date >> ~/modinstall.script
+date > ${SCRPT}
+make O=${KERNEL_BUILD} ARCH=arm CROSS_COMPILE=${CCPREFIX} INSTALL_MOD_PATH=${MODULES_TEMP} modules_install &>> ${SCRPT}
+RES=$?
+date >> ${SCRPT}
+exit ${RES}
 
 
 
